"""
Pull Request creation with inline review comments.

Creates a PR and adds inline code review comments explaining:
- What vulnerability was found
- Why the change was made
- What the fix does

Uses GitHub's Pull Request Review API to post comments
directly on the changed lines — just like a human reviewer.
"""

import os
import logging
from typing import List, Dict, Any, Optional

logger = logging.getLogger(__name__)


def create_pr(
    repo_name: str,
    branch_name: str,
    default_branch: str = "",
    fixed_files: Optional[List[Dict[str, Any]]] = None,
    findings: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """
    Create a Pull Request on GitHub with inline review comments.

    Args:
        repo_name: "owner/repo"
        branch_name: branch with fixes
        default_branch: target branch (empty = auto-detect from repo)
        fixed_files: list of {"path", "findings_fixed", "confidence", "diff"}
        findings: original findings that were fixed
    """
    from github import Github

    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise Exception("GITHUB_TOKEN not set in .env - cannot create Pull Request")

    g = Github(token)
    repo = g.get_repo(repo_name)

    # Use repo's actual default branch (main, master, develop, etc.)
    base_branch = default_branch or repo.default_branch
    logger.info(f"Creating PR: {branch_name} -> {base_branch} on {repo_name}")

    # Build PR body with summary
    body = _build_pr_body(fixed_files, findings)

    pr = repo.create_pull(
        title="fix(security): AI vulnerability remediation",
        body=body,
        head=branch_name,
        base=base_branch,
    )

    logger.info(f"PR created: {pr.html_url}")

    # Add inline review comments explaining each fix
    if findings and fixed_files:
        _add_review_comments(repo, pr, findings, fixed_files, branch_name)

    return pr.html_url


def _build_pr_body(
    fixed_files: Optional[List[Dict]] = None,
    findings: Optional[List[Dict]] = None,
) -> str:
    """Build a detailed PR description."""
    body = "## 🛡️ Automated Security Remediation\n\n"
    body += "This PR was generated by the **AI Vulnerability Remediator**.\n\n"

    if fixed_files:
        total_fixed = sum(f.get("findings_fixed", 0) for f in fixed_files)
        avg_confidence = 0
        confidence_files = [f for f in fixed_files if f.get("confidence", -1) >= 0]
        if confidence_files:
            avg_confidence = sum(f["confidence"] for f in confidence_files) / len(confidence_files)

        body += "### Summary\n\n"
        body += f"| Metric | Value |\n|---|---|\n"
        body += f"| Files fixed | {len(fixed_files)} |\n"
        body += f"| Vulnerabilities resolved | {total_fixed} |\n"
        if avg_confidence > 0:
            body += f"| Average fix confidence | {avg_confidence:.0f}% |\n"
        body += "\n"

        # Issue Found → Fixed table
        body += "### Issues Fixed by AI Vulnerability Remediator\n\n"
        body += "| # | Issue Found | Fixed By | File |\n"
        body += "|:-:|-------------|----------|------|\n"
        fix_num = 0
        for f in fixed_files:
            fix_details = f.get("fix_details", [])
            if fix_details:
                for detail in fix_details:
                    fix_num += 1
                    body += f"| {fix_num} | ⚠️ {detail.get('issue', '')} | ✅ {detail.get('fixed_by', 'Fixed by AI')} | `{f['path']}` |\n"
            else:
                fix_num += 1
                body += f"| {fix_num} | ⚠️ {f.get('findings_fixed', 0)} vulnerability(s) | ✅ Fixed by AI Vulnerability Remediator | `{f['path']}` |\n"
        body += "\n"

        # Files table
        body += "### Files Changed\n\n"
        body += "| File | Issues Fixed | Confidence | Changes |\n"
        body += "|------|:-----------:|:----------:|:-------:|\n"
        for f in fixed_files:
            conf = f"{f['confidence']}%" if f.get("confidence", -1) >= 0 else "—"
            diff = f"+{f['diff']['additions']} -{f['diff']['deletions']}" if f.get("diff") else "—"
            body += f"| `{f['path']}` | {f.get('findings_fixed', 0)} | {conf} | {diff} |\n"
        body += "\n"

    # Vulnerability types found
    if findings:
        severity_counts: Dict[str, int] = {}
        for f in findings:
            sev = f.get("severity", "MEDIUM")
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        body += "### Vulnerabilities Addressed\n\n"
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
            count = severity_counts.get(sev, 0)
            if count:
                emoji = "🔴" if sev == "CRITICAL" else "🟠" if sev == "HIGH" else "🟡" if sev == "MEDIUM" else "🔵"
                body += f"- {emoji} **{sev}**: {count}\n"
        body += "\n"

    body += "---\n"
    body += "⚠️ **Please review the changes carefully before merging.**\n\n"
    body += "_Generated by [AI Vulnerability Remediator](https://github.com) — "
    body += "inline review comments explain each change._\n"

    return body


def _add_review_comments(
    repo,
    pr,
    findings: List[Dict[str, Any]],
    fixed_files: List[Dict[str, Any]],
    branch_name: str,
):
    """
    Add inline review comments on the PR explaining each fix.
    Uses GitHub's Pull Request Review API.
    """
    try:
        # Get the latest commit on the PR
        commits = list(pr.get_commits())
        if not commits:
            logger.warning("No commits found on PR, skipping review comments")
            return

        latest_commit = commits[-1]
        commit_sha = latest_commit.sha

        # Group findings by file
        findings_by_file: Dict[str, List[Dict]] = {}
        for f in findings:
            path = f.get("path", "")
            if path:
                if path not in findings_by_file:
                    findings_by_file[path] = []
                findings_by_file[path].append(f)

        # Build review comments
        comments = []
        for fixed_file in fixed_files:
            file_path = fixed_file.get("path", "")
            file_findings = findings_by_file.get(file_path, [])

            if not file_findings:
                continue

            for finding in file_findings[:5]:  # Max 5 comments per file
                line = finding.get("line")
                if not line:
                    continue

                comment_body = _build_comment(finding, fixed_file)
                comments.append({
                    "path": file_path,
                    "line": line,
                    "body": comment_body,
                })

        if not comments:
            logger.info("No inline comments to add")
            return

        # Submit as a PR review with all comments at once
        # GitHub requires either:
        # - "position" (line in the diff hunk) — fragile, hard to calculate
        # - "line" + "side" (absolute file line) — newer API, more reliable
        review_comments = []
        for c in comments[:20]:  # GitHub limits to ~20 comments per review
            review_comments.append({
                "path": c["path"],
                "line": c["line"],
                "side": "RIGHT",  # Comment on the new (fixed) version
                "body": c["body"],
            })

        # Use create_review for batch comments
        try:
            pr.create_review(
                commit=latest_commit,
                body="## 🤖 AI Security Review\n\nInline comments explain each vulnerability fix.",
                event="COMMENT",
                comments=review_comments,
            )
            logger.info(f"Added {len(review_comments)} inline review comments to PR")
        except Exception as review_err:
            # If review API fails, fall back to a single summary comment
            logger.warning(f"Batch review failed ({review_err}), posting summary comment...")
            _add_summary_comment(pr, comments)

    except Exception as e:
        # Don't fail the PR creation if comments fail
        logger.error(f"Failed to add review comments: {e}")


def _add_individual_comments(pr, comments: List[Dict], commit):
    """Fallback: add a single summary comment with all findings."""
    _add_summary_comment(pr, comments)


def _add_summary_comment(pr, comments: List[Dict]):
    """Post a single PR comment summarizing all fixes (reliable fallback)."""
    try:
        body = "## 🤖 AI Security Review — Fix Details\n\n"
        body += "Inline comments could not be placed on exact diff lines. "
        body += "Here's a summary of all fixes:\n\n"

        for i, c in enumerate(comments[:15], 1):
            body += f"### {i}. `{c['path']}` (line {c['line']})\n\n"
            body += c["body"] + "\n\n---\n\n"

        pr.create_issue_comment(body)
        logger.info(f"Added summary review comment with {len(comments)} findings")
    except Exception as e:
        logger.error(f"Failed to add summary comment: {e}")


def _build_comment(finding: Dict[str, Any], fixed_file: Dict[str, Any]) -> str:
    """Build a human-readable review comment for a finding."""
    severity = finding.get("severity", "MEDIUM")
    rule_id = finding.get("rule_id", "unknown")
    message = finding.get("message", "")
    category = finding.get("metadata", {}).get("category", "")
    fix_guidance = finding.get("metadata", {}).get("fix_guidance", "")

    # Severity emoji
    emoji = "🔴" if severity == "CRITICAL" else "🟠" if severity == "HIGH" else "🟡" if severity == "MEDIUM" else "🔵"

    comment = f"{emoji} **{severity}** — `{rule_id}`\n\n"
    comment += f"**What was found:** {message[:200]}\n\n"

    # Why it's dangerous
    risk_explanation = _get_risk_explanation(rule_id, category)
    if risk_explanation:
        comment += f"**Why it's dangerous:** {risk_explanation}\n\n"

    # What the fix does
    if fix_guidance:
        comment += f"**Fix applied:** {fix_guidance}\n\n"
    else:
        comment += f"**Fix applied:** Vulnerability pattern removed and replaced with secure alternative.\n\n"

    # Confidence
    confidence = fixed_file.get("confidence", -1)
    if confidence >= 0:
        conf_emoji = "✅" if confidence >= 90 else "⚠️" if confidence >= 70 else "❓"
        comment += f"{conf_emoji} Fix confidence: **{confidence}%**\n"

    return comment


def _get_risk_explanation(rule_id: str, category: str) -> str:
    """Get a human-readable risk explanation for common vulnerability types."""
    rule_lower = rule_id.lower()

    explanations = {
        "sql": "An attacker could manipulate database queries to steal, modify, or delete data. This can lead to full database compromise.",
        "xss": "An attacker could inject malicious scripts that execute in other users' browsers, stealing sessions, credentials, or personal data.",
        "command": "An attacker could execute arbitrary system commands on the server, potentially gaining full control of the machine.",
        "path-traversal": "An attacker could read or write files outside the intended directory, potentially accessing sensitive configuration or system files.",
        "deserialization": "An attacker could execute arbitrary code by sending crafted serialized data, leading to remote code execution.",
        "secret": "Hardcoded credentials in source code can be extracted by anyone with repository access, leading to unauthorized access to systems.",
        "csrf": "An attacker could trick authenticated users into performing unintended actions on the application.",
        "ssrf": "An attacker could make the server send requests to internal systems, potentially accessing private APIs or metadata services.",
        "redirect": "An attacker could redirect users to malicious websites, enabling phishing attacks.",
        "crypto": "Weak cryptographic algorithms can be broken, exposing encrypted data to attackers.",
        "auth": "Authentication bypass allows attackers to access protected resources without valid credentials.",
    }

    for keyword, explanation in explanations.items():
        if keyword in rule_lower or keyword in category.lower():
            return explanation

    return ""
