import os
import logging

logger = logging.getLogger(__name__)


def create_pr(repo_name: str, branch_name: str, default_branch: str = "main"):
    """
    Create a Pull Request on GitHub.
    """
    from github import Github

    token = os.getenv("GITHUB_TOKEN")

    if not token:
        raise Exception(
            "GITHUB_TOKEN not set in .env - cannot create Pull Request"
        )

    g = Github(token)
    repo = g.get_repo(repo_name)

    # Use the repo's actual default branch
    base_branch = default_branch or repo.default_branch
    logger.info(f"Creating PR: {branch_name} -> {base_branch} on {repo_name}")

    pr = repo.create_pull(
        title="fix(security): AI vulnerability remediation",
        body=(
            "## Automated Security Remediation\n\n"
            "This PR was generated by the AI Vulnerability Remediator.\n\n"
            "**Changes:**\n"
            "- Fixed source code vulnerabilities detected by Semgrep\n\n"
            "**Please review the changes carefully before merging.**"
        ),
        head=branch_name,
        base=base_branch,
    )

    logger.info(f"PR created: {pr.html_url}")
    return pr.html_url
