"""
LLM Analyzer — AI-powered vulnerability fix generation.

Optimizations:
- Smart context extraction (sends only relevant code, not entire file)
- Token-efficient prompts (structured, minimal)
- Fix caching (same issue + same code = cached result)
- Prompt compression (removes unnecessary whitespace/comments from context)
"""

import hashlib
import logging
from typing import Optional, List, Dict, Any

from app.llm.skill_loader import load_skill
from app.llm.llm_router import router as llm_router
from app.llm.context_extractor import extract_relevant_context, reconstruct_full_file, estimate_tokens

logger = logging.getLogger(__name__)

# Load the skill prompt once
skill = load_skill()

# Simple in-memory fix cache (avoids re-calling LLM for same issue)
_fix_cache: Dict[str, str] = {}
_MAX_CACHE_SIZE = 100


def analyze_and_fix(
    code: str,
    issue: str,
    file_path: str = "",
    findings: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """
    Use the LLM router to generate a fix for the vulnerability.

    Optimizations applied:
    1. Context extraction — only sends relevant function/block (60-80% token savings)
    2. Caching — same code + issue returns cached fix
    3. Compressed prompt — minimal tokens, maximum clarity
    """
    # Check cache first
    cache_key = _cache_key(code, issue)
    if cache_key in _fix_cache:
        logger.info("Fix cache hit — returning cached result")
        return _fix_cache[cache_key]

    # Extract minimal context (reduces tokens significantly)
    if findings and file_path:
        context = extract_relevant_context(code, findings, file_path)
        context_code = context["context_code"]
        savings = context["token_savings_pct"]
        if savings > 0:
            logger.info(f"Context extraction saved {savings:.0f}% tokens ({estimate_tokens(code)} → {estimate_tokens(context_code)})")
    else:
        context_code = code
        context = {"line_offset": 0, "full_code": code}

    # Build optimized prompt
    prompt = _build_prompt(context_code, issue)

    logger.info(f"LLM prompt: ~{estimate_tokens(prompt)} tokens")

    # Call LLM
    result, provider_name = llm_router.generate(prompt)
    logger.info(f"Fix generated by: {provider_name} (~{estimate_tokens(result)} tokens)")

    # Strip markdown code fences
    fixed_code = _strip_code_fences(result)

    # If we only sent a context window, reconstruct the full file
    if context.get("token_savings_pct", 0) > 0 and context.get("line_offset", 0) > 0:
        context_lines = len(context_code.splitlines())
        fixed_code = reconstruct_full_file(
            code, fixed_code, context["line_offset"], context_lines
        )

    # Cache the result
    _cache_fix(cache_key, fixed_code)

    return fixed_code


def _build_prompt(code: str, issue: str) -> str:
    """
    Build a token-efficient prompt.
    Uses a focused fix prompt instead of the full skill file.
    The skill file is designed for CSV-based remediation workflows —
    for direct code fixing, a compact prompt works better.
    """
    return f"""You are a senior security engineer fixing vulnerabilities in production code.

RULES:
- Return ONLY the complete fixed code
- No explanations, no markdown fences, no comments about changes
- Preserve all existing functionality
- Use environment variables for secrets/credentials (process.env, os.environ, System.getenv)
- Keep the same code style, indentation, and language
- If fixing SQL injection: use parameterized queries
- If fixing XSS: use proper escaping/sanitization
- If fixing hardcoded secrets: replace with environment variable with a dev fallback
- If fixing command injection: use safe APIs, avoid shell=True
- If fixing path traversal: validate and sanitize file paths

VULNERABILITY:
{issue}

CODE TO FIX:
{code}"""


def _strip_code_fences(text: str) -> str:
    """Remove markdown code fences from LLM output."""
    text = text.strip()

    if text.startswith("```"):
        lines = text.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines)

    return text


def _cache_key(code: str, issue: str) -> str:
    """Generate a cache key from code + issue."""
    combined = f"{code[:200]}|{issue[:200]}"
    return hashlib.md5(combined.encode()).hexdigest()


def _cache_fix(key: str, fixed_code: str):
    """Store fix in cache with size limit."""
    global _fix_cache
    if len(_fix_cache) >= _MAX_CACHE_SIZE:
        # Remove oldest entries (FIFO)
        oldest_keys = list(_fix_cache.keys())[:_MAX_CACHE_SIZE // 2]
        for k in oldest_keys:
            del _fix_cache[k]
    _fix_cache[key] = fixed_code
