import logging
from app.llm.skill_loader import load_skill
from app.llm.llm_router import router as llm_router

logger = logging.getLogger(__name__)

# Load the skill prompt
skill = load_skill()


def analyze_and_fix(code: str, issue: str) -> str:
    """
    Use the LLM router to generate a fix for the vulnerability.
    Automatically falls through providers: Gemini → NVIDIA → OpenRouter
    """
    prompt = f"""
{skill}

You are a senior security engineer.

Fix the vulnerability.

Issue:
{issue}

Code:
{code}

Return ONLY the fixed code. No explanations, no markdown code fences, no comments about what was changed.
"""

    logger.info("Requesting vulnerability fix from LLM...")

    result, provider_name = llm_router.generate(prompt)
    logger.info(f"Fix generated by: {provider_name}")

    # Strip markdown code fences if present
    fixed_code = _strip_code_fences(result)

    return fixed_code


def _strip_code_fences(text: str) -> str:
    """Remove markdown code fences from LLM output."""
    text = text.strip()

    if text.startswith("```"):
        lines = text.split("\n")
        # Remove first line (```language)
        if lines[0].startswith("```"):
            lines = lines[1:]
        # Remove last line (```)
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines)

    return text
